services:
  - type: web
    name: artify-ai-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: REPLICATE_API_TOKEN
        sync: false
